//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtobusBiletSatis
{
    using System;
    using System.Collections.Generic;
    
    public partial class adres
    {
        public adres()
        {
            this.calisan = new HashSet<calisan>();
            this.molaTesis = new HashSet<molaTesis>();
            this.musteri = new HashSet<musteri>();
            this.sube = new HashSet<sube>();
        }
    
        public int adresID { get; set; }
        public Nullable<int> sehirID { get; set; }
        public Nullable<int> ilceID { get; set; }
        public Nullable<int> mahalleID { get; set; }
        public string aciklama { get; set; }
    
        public virtual ICollection<calisan> calisan { get; set; }
        public virtual ICollection<molaTesis> molaTesis { get; set; }
        public virtual ICollection<musteri> musteri { get; set; }
        public virtual ICollection<sube> sube { get; set; }
    }
}
