//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtobusBiletSatis
{
    using System;
    using System.Collections.Generic;
    
    public partial class basvurular
    {
        public int basvuruid { get; set; }
        public string ad_soyad { get; set; }
        public string dogumyeri { get; set; }
        public System.DateTime dogumtarihi { get; set; }
        public string medenihal { get; set; }
        public string tel { get; set; }
        public string mail { get; set; }
        public string ikametadresi { get; set; }
        public string kısabilgi { get; set; }
        public string dosya { get; set; }
        public bool durum { get; set; }
    }
}
