//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtobusBiletSatis
{
    using System;
    using System.Collections.Generic;
    
    public partial class calisanKullanici
    {
        public int calisanKullanici1 { get; set; }
        public int calisanID { get; set; }
        public string kadi { get; set; }
        public string sifre { get; set; }
        public bool durum { get; set; }
    
        public virtual calisan calisan { get; set; }
    }
}
