//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtobusBiletSatis
{
    using System;
    using System.Collections.Generic;
    
    public partial class guzergahDurak
    {
        public int guzergahDurakID { get; set; }
        public int guzergahID { get; set; }
        public int subeID { get; set; }
        public int sira { get; set; }
        public int kilometre { get; set; }
    
        public virtual guzergah guzergah { get; set; }
    }
}
