//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtobusBiletSatis
{
    using System;
    using System.Collections.Generic;
    
    public partial class koltuk
    {
        public int koltukID { get; set; }
        public int seferID { get; set; }
        public int musteriID { get; set; }
        public int guzergahDurakSira { get; set; }
        public int koltukNo { get; set; }
        public bool durum { get; set; }
    
        public virtual musteri musteri { get; set; }
        public virtual sefer sefer { get; set; }
    }
}
