//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtobusBiletSatis
{
    using System;
    using System.Collections.Generic;
    
    public partial class otobusMarka
    {
        public otobusMarka()
        {
            this.otobusModel = new HashSet<otobusModel>();
        }
    
        public int otobusMarkaID { get; set; }
        public string ad { get; set; }
        public string aciklama { get; set; }
        public bool durum { get; set; }
    
        public virtual ICollection<otobusModel> otobusModel { get; set; }
    }
}
