//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtobusBiletSatis
{
    using System;
    using System.Collections.Generic;
    
    public partial class otobus
    {
        public otobus()
        {
            this.sefer = new HashSet<sefer>();
        }
    
        public int otobusID { get; set; }
        public string saseNumarasi { get; set; }
        public string plaka { get; set; }
        public int otobusModelID { get; set; }
        public System.DateTime uretimYili { get; set; }
        public bool durum { get; set; }
    
        public virtual otobusModel otobusModel { get; set; }
        public virtual ICollection<sefer> sefer { get; set; }
    }
}
