//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtobusBiletSatis
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class otobusEntities : DbContext
    {
        public otobusEntities()
            : base("name=otobusEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<adres> adres { get; set; }
        public DbSet<basvurular> basvurular { get; set; }
        public DbSet<bilet> bilet { get; set; }
        public DbSet<calisan> calisan { get; set; }
        public DbSet<calisanKullanici> calisanKullanici { get; set; }
        public DbSet<calisanPozisyon> calisanPozisyon { get; set; }
        public DbSet<guzergah> guzergah { get; set; }
        public DbSet<guzergahDurak> guzergahDurak { get; set; }
        public DbSet<guzergahMola> guzergahMola { get; set; }
        public DbSet<ilce> ilce { get; set; }
        public DbSet<koltuk> koltuk { get; set; }
        public DbSet<mahalle> mahalle { get; set; }
        public DbSet<molaTesis> molaTesis { get; set; }
        public DbSet<musteri> musteri { get; set; }
        public DbSet<otobus> otobus { get; set; }
        public DbSet<otobusMarka> otobusMarka { get; set; }
        public DbSet<otobusModel> otobusModel { get; set; }
        public DbSet<sefer> sefer { get; set; }
        public DbSet<seferCalisan> seferCalisan { get; set; }
        public DbSet<sehir> sehir { get; set; }
        public DbSet<sube> sube { get; set; }
    
        public virtual int sp_guzergahUpdate(Nullable<int> guzergahID, string guzergahAd, string guzergahAciklama)
        {
            var guzergahIDParameter = guzergahID.HasValue ?
                new ObjectParameter("guzergahID", guzergahID) :
                new ObjectParameter("guzergahID", typeof(int));
    
            var guzergahAdParameter = guzergahAd != null ?
                new ObjectParameter("guzergahAd", guzergahAd) :
                new ObjectParameter("guzergahAd", typeof(string));
    
            var guzergahAciklamaParameter = guzergahAciklama != null ?
                new ObjectParameter("guzergahAciklama", guzergahAciklama) :
                new ObjectParameter("guzergahAciklama", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_guzergahUpdate", guzergahIDParameter, guzergahAdParameter, guzergahAciklamaParameter);
        }
    
        public virtual ObjectResult<sp_seferDetaylariGetir_Result1> sp_seferDetaylariGetir(Nullable<int> guzergahID, Nullable<int> neredenSubeID, Nullable<int> nereyeSubeID)
        {
            var guzergahIDParameter = guzergahID.HasValue ?
                new ObjectParameter("guzergahID", guzergahID) :
                new ObjectParameter("guzergahID", typeof(int));
    
            var neredenSubeIDParameter = neredenSubeID.HasValue ?
                new ObjectParameter("neredenSubeID", neredenSubeID) :
                new ObjectParameter("neredenSubeID", typeof(int));
    
            var nereyeSubeIDParameter = nereyeSubeID.HasValue ?
                new ObjectParameter("nereyeSubeID", nereyeSubeID) :
                new ObjectParameter("nereyeSubeID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_seferDetaylariGetir_Result1>("sp_seferDetaylariGetir", guzergahIDParameter, neredenSubeIDParameter, nereyeSubeIDParameter);
        }
    
        public virtual ObjectResult<Nullable<bool>> sp_seferFiltreleByYon(Nullable<int> guzergahID, Nullable<int> neredenSubeID, Nullable<int> nereyeSubeID)
        {
            var guzergahIDParameter = guzergahID.HasValue ?
                new ObjectParameter("guzergahID", guzergahID) :
                new ObjectParameter("guzergahID", typeof(int));
    
            var neredenSubeIDParameter = neredenSubeID.HasValue ?
                new ObjectParameter("neredenSubeID", neredenSubeID) :
                new ObjectParameter("neredenSubeID", typeof(int));
    
            var nereyeSubeIDParameter = nereyeSubeID.HasValue ?
                new ObjectParameter("nereyeSubeID", nereyeSubeID) :
                new ObjectParameter("nereyeSubeID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<bool>>("sp_seferFiltreleByYon", guzergahIDParameter, neredenSubeIDParameter, nereyeSubeIDParameter);
        }
    
        public virtual ObjectResult<sp_seferGetirByGuzergahAndTarih_Result> sp_seferGetirByGuzergahAndTarih(Nullable<int> neredenSubeID, Nullable<int> nereyeSubeID, Nullable<System.DateTime> kalkisTarihi)
        {
            var neredenSubeIDParameter = neredenSubeID.HasValue ?
                new ObjectParameter("neredenSubeID", neredenSubeID) :
                new ObjectParameter("neredenSubeID", typeof(int));
    
            var nereyeSubeIDParameter = nereyeSubeID.HasValue ?
                new ObjectParameter("nereyeSubeID", nereyeSubeID) :
                new ObjectParameter("nereyeSubeID", typeof(int));
    
            var kalkisTarihiParameter = kalkisTarihi.HasValue ?
                new ObjectParameter("kalkisTarihi", kalkisTarihi) :
                new ObjectParameter("kalkisTarihi", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_seferGetirByGuzergahAndTarih_Result>("sp_seferGetirByGuzergahAndTarih", neredenSubeIDParameter, nereyeSubeIDParameter, kalkisTarihiParameter);
        }
    }
}
