//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtobusBiletSatis
{
    using System;
    using System.Collections.Generic;
    
    public partial class otobusModel
    {
        public otobusModel()
        {
            this.otobus = new HashSet<otobus>();
        }
    
        public int otobusModelID { get; set; }
        public int otobusMarkaID { get; set; }
        public string ad { get; set; }
        public int koltukSayisi { get; set; }
        public bool durum { get; set; }
    
        public virtual ICollection<otobus> otobus { get; set; }
        public virtual otobusMarka otobusMarka { get; set; }
    }
}
