//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtobusBiletSatis
{
    using System;
    using System.Collections.Generic;
    
    public partial class sefer
    {
        public sefer()
        {
            this.bilet = new HashSet<bilet>();
            this.koltuk = new HashSet<koltuk>();
            this.seferCalisan = new HashSet<seferCalisan>();
        }
    
        public int seferID { get; set; }
        public Nullable<int> otobusID { get; set; }
        public System.DateTime kalkisTarihi { get; set; }
        public int guzergahID { get; set; }
        public bool durum { get; set; }
        public bool yon { get; set; }
    
        public virtual ICollection<bilet> bilet { get; set; }
        public virtual guzergah guzergah { get; set; }
        public virtual ICollection<koltuk> koltuk { get; set; }
        public virtual otobus otobus { get; set; }
        public virtual ICollection<seferCalisan> seferCalisan { get; set; }
    }
}
