//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtobusBiletSatis
{
    using System;
    
    public partial class sp_seferGetirByGuzergahAndTarih_Result
    {
        public bool yon { get; set; }
        public int guzergahID { get; set; }
        public int seferID { get; set; }
        public string ad { get; set; }
        public System.DateTime kalkisTarihi { get; set; }
    }
}
