//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtobusBiletSatis
{
    using System;
    
    public partial class sp_seferDetaylariGetir_Result1
    {
        public Nullable<int> molaSayisi { get; set; }
        public Nullable<int> mesafe { get; set; }
        public Nullable<int> neredenSira { get; set; }
        public Nullable<int> nereyeSira { get; set; }
    }
}
