//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtobusBiletSatis
{
    using System;
    using System.Collections.Generic;
    
    public partial class sube
    {
        public sube()
        {
            this.calisan = new HashSet<calisan>();
        }
    
        public int subeID { get; set; }
        public string ad { get; set; }
        public int adresID { get; set; }
        public System.DateTime acilisTarihi { get; set; }
        public bool durum { get; set; }
        public string telefon { get; set; }
        public string mail { get; set; }
    
        public virtual adres adres { get; set; }
        public virtual ICollection<calisan> calisan { get; set; }
    }
}
